### PR TITLE
Add missing Zima variants. Fixes #139

### LINKED ISSUE #139: Missing Zima variants in vehicle dictionary
Entries for variants `BP_Niva_05_C`, `BP_Niva_06_C` and `BP_Niva_07_C` are missing.

### PR DESCRIPTION
**Pull request by DennisBirkholz**
Fixes #139.

### CODE REVIEW

**Comment by thedarkman** [comment]
Hi Dennis, those variants are missing in `damageCauserName.json` also, right?

**Comment by DennisBirkholz** [comment]
The `damageCauserName.json` file is a bit different as the damage causer names are not necessarily real item/vehicle ids as you see with all the weapon names. I did not encounter the missing Zima variants as damage causers so I do not know if they can appear or are mapped to something else.

**Comment by thedarkman** [comment]
Well, i had this in one telemetry event

`"damageCauserName":"BP_Niva_05_C"`

and that value was not in the `damageCauserName.json` file.
All other variants are there, so i added it in my code. 
But when you say it does not need to be there, never mind ;).

I can give you match id if you want.

**Comment by DennisBirkholz** [comment]
> But when you say it does not need to be there, never mind ;).

I did not say that, I just did not encounter it before. But feel free to create a pull request with the additional names in the `damageCauserName.json`, I am sure the PUBG folks will consider it! But it is not up to me, I am not affiliated with PUBG or have any say in what will be merged into this repository

**Comment by thedarkman** [comment]
> But feel free to create a pull request with the additional names in the damageCauserName.json, I am sure the PUBG folks will consider it!

Hi Dennis, i'm not used to github , how is the desired procedure? Do i create a local branch and push it with my changes and then create pull request to master or how will it work? 
Or do i fork the repository on github?

If i could contribute i would fix #150, #154 and those Zima variants entries in the `damageCauserName.json`.

**Comment by DennisBirkholz** [comment]
> Hi Dennis, i'm not used to github , how is the desired procedure? Do i create a local branch and push it with my changes and then create pull request to master or how will it work?
> Or do i fork the repository on github?

I think the procedure is: fork the repository on github, push your fixes to your forked repo (to any branch you want, does not matter), create a pull request for that branch. You can create the pull request directly from your forked repository.

**Pull request merged**
